services:
  - type: web
    name: tender-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update &&
      apt-get update && apt-get install -y chromium-browser chromium-driver
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
