services:
  - type: web
    name: tender-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update &&
      apt-get install -y chromium-browser &&
      pip install -r requirements.txt
    startCommand: python bot.py
